server:
  port: 8081  #服务端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wugk_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql   #jpa数据库支持
    show-sql: true    #jpa打印sql语句
