server:
  port: 8088  #服务端口
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wugk_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
      host: localhost
      port: 5672
#      username: guest
#      password: guest
  jpa:
    database: mysql   #jpa数据库支持
    show-sql: true    #jpa打印sql语句
